import { validatePocxAddress, type AddressValidation } from './address-validation';

/**
 * BIP21-style payment URIs for Bitcoin-PoCX.
 *
 * Outbound (QR + copied URI) uses the canonical `btcx:` scheme — matching the
 * BTCX ticker shown throughout the UI and every QR already generated by the
 * Receive page. Inbound parsing additionally accepts `pocx:` (the address HRP)
 * and `bitcoin:` (the PoCX node's Qt wallet still emits `bitcoin:` URIs —
 * `bitcoin/src/qt/guiutil.cpp` was never rebranded; slated for a node amend to
 * `btcx:`), plus a bare address with no scheme. Every parsed address is
 * validated against the PoCX HRPs, so a real Bitcoin `bitcoin:bc1…` URI is
 * still rejected as wrong-network — accepting the scheme only helps PoCX QRs.
 */

/** Schemes accepted on inbound parse (case-insensitive). */
export const ACCEPTED_URI_SCHEMES = ['btcx', 'pocx', 'bitcoin'] as const;
/** Scheme WE emit when building a URI / QR. Keep receive + parser in sync. */
export const CANONICAL_URI_SCHEME = 'btcx';

export interface ParsedPaymentUri {
  /** Bare address, scheme + query stripped. */
  address: string;
  /** Requested amount in whole BTCX, or null when absent/invalid. */
  amount: number | null;
  label: string | null;
  message: string | null;
  /** Result of validating the extracted address. */
  validation: AddressValidation;
}

/**
 * Parse a BIP21-style payment URI OR a bare address.
 *
 * Accepts `btcx:addr?amount=1.5&label=x`, `pocx://addr`, and a bare `addr`.
 * Returns null only when the input is blank. Otherwise always returns a
 * result; callers inspect `.validation.kind` (and compare the network to the
 * app's own) exactly as they already do for a hand-typed address.
 */
export function parsePaymentUri(input: string): ParsedPaymentUri | null {
  const raw = (input ?? '').trim();
  if (!raw) return null;

  let rest = raw;
  const colon = rest.indexOf(':');
  if (colon > 0) {
    const scheme = rest.slice(0, colon).toLowerCase();
    if ((ACCEPTED_URI_SCHEMES as readonly string[]).includes(scheme)) {
      // strip scheme + an optional "//"
      rest = rest.slice(colon + 1).replace(/^\/\//, '');
    }
    // else: not our scheme — a bare bech32 address has no colon, so treat the
    // whole input as the address and let validation reject anything odd.
  }

  const qIndex = rest.indexOf('?');
  const address = (qIndex >= 0 ? rest.slice(0, qIndex) : rest).trim();
  const params = new URLSearchParams(qIndex >= 0 ? rest.slice(qIndex + 1) : '');

  const amountRaw = params.get('amount');
  const amountNum = amountRaw != null ? Number(amountRaw) : NaN;
  const amount = Number.isFinite(amountNum) && amountNum > 0 ? amountNum : null;

  return {
    address,
    amount,
    label: params.get('label'),
    message: params.get('message'),
    validation: validatePocxAddress(address),
  };
}

/** Build our canonical outbound payment URI (used by Receive + tests). */
export function buildPaymentUri(opts: {
  address: string;
  amount?: number | null;
  label?: string | null;
  message?: string | null;
}): string {
  if (!opts.address) return '';
  const params = new URLSearchParams();
  if (opts.amount && opts.amount > 0) params.set('amount', String(opts.amount));
  if (opts.label?.trim()) params.set('label', opts.label.trim());
  if (opts.message?.trim()) params.set('message', opts.message.trim());
  const qs = params.toString();
  return `${CANONICAL_URI_SCHEME}:${opts.address}${qs ? '?' + qs : ''}`;
}
